#!/usr/bin/env bash
# Transfer file from client to server take 4 path

path="$1"
ip="$2"
username="$3"
ssh_key="$4"

	if [ $# == 4 ]
	then
		scp -o StrictHostKeyChecking=no -i "$ssh_key" "$path" "$username@$ip:~"
	else
		echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	fi

