#!/usr/bin/env bash
# Install nginx with the following configuration
# Listen to port 80
# Returns a page "Hello World" when queried
# at the root with Get request.

# Install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configuration
mkdir /etc/nginx/html

# Creating Sample Page
touch /etc/nginx/html/index.html
echo "Hello World" > /etc/nginx/html/index.html

# Creating the Server Block File
echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	
	root /etc/nginx/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
}
" > /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
