#!/usr/bin/env bash
#A script that display 1 to 100
#Display FizzBuzz at multiple of 3 and 5
#Display Fizz at multiple pf 3
#Display Buzz at multiple of 5

for i in {1..100}
do
	if [ $((i % 3)) -eq 0 ]  &&  [ $((i % 5)) -eq  0 ]
	then
		echo "FizzBuzz"
	elif [ $((i % 3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $((i % 5)) -eq 0 ]
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done
