#!/usr/bin/env bash
: '
Display number 20 times
Display "bad luck from China" for the 4th loop
Display "bad luck from Japan" for the 9th loop
Display "bad luck from Italy" for the 9th loop'

i=1

while [ $i -le 20 ]
do
		echo "$i"
		case $i in
			"4")echo "bad luck from China"
			;;
			"9")echo "bad luck from Japan"
			;;
			"17")echo "bad luck from Italy"
			;;
		esac
		(( i++ ))
done
