#!/usr/bin/env bash
: '
script display content of current directory
in a list format,  while onnly part of the name
after the first dash is displayed'

list=$(ls)

for i in $list
do
	echo "$i" | cut -d '-' -f2
done
