#!/usr/bin/env bash
: '
Write a Bash script that configures an Ubuntu
 server with the following requirements 
localhost resolves to 127.0.0.2
facebook.com resolves to 8.8.8.8'

cp /etc/hosts ~/hosts.home
echo "127.0.0.2		localhost" > ~/hosts.home
echo "8.8.8.8		facebook.come" >> ~/hosts.home
cp -f ~/hosts.home /etc/hosts
