#!/usr/bin/env bash
# A script that creates a ssh key pair with 4096 bit
# Name of created private key is school
# created key protected by the passphrase betty

ssh-keygen -t rsa -b 4096 -f school -N betty
